const page_prices = [
  {
    range: "$100k-$200k",
    id: 1,
    data: [
      {
        name: "Qualified 20",
        leads_per_month: "20",
        price: "$69",
        total_qualified_lead_price: "$1,380",
        total_platform_price: "$299",
        final_package_price: "$1,679",
      },
      {
        name: "Qualified 40",
        leads_per_month: "40",
        price: "$67",
        total_qualified_lead_price: "$2,680",
        total_platform_price: "$599",
        final_package_price: "$3,279",
      },
      {
        name: "Qualified 60",
        leads_per_month: "60",
        price: "$65",
        total_qualified_lead_price: "$3,900",
        total_platform_price: "$699",
        final_package_price: "$4,599",
      },
      {
        name: "Qualified 80",
        leads_per_month: "80",
        price: "$63",
        total_qualified_lead_price: "$5,040",
        total_platform_price: "$799",
        final_package_price: "$5,839",
      },
    ],
  },
  {
    range: "$200k-$300k",
    id: 2,
    data: [
      {
        name: "Qualified 20",
        leads_per_month: "20",
        price: "$79",
        total_qualified_lead_price: "$1,580",
        total_platform_price: "$299",
        final_package_price: "$1,879",
      },
      {
        name: "Qualified 40",
        leads_per_month: "40",
        price: "$77",
        total_qualified_lead_price: "$3,080",
        total_platform_price: "$599",
        final_package_price: "$3,679",
      },
      {
        name: "Qualified 60",
        leads_per_month: "60",
        price: "$74",
        total_qualified_lead_price: "$4,440",
        total_platform_price: "$699",
        final_package_price: "$5,139",
      },
      {
        name: "Qualified 80",
        leads_per_month: "80",
        price: "$72",
        total_qualified_lead_price: "$5,760",
        total_platform_price: "$799",
        final_package_price: "$6,559",
      },
    ],
  },
  {
    range: "$300k-$400k",
    id: 3,
    data: [
      {
        name: "Qualified 20",
        leads_per_month: "20",
        price: "$99",
        total_qualified_lead_price: "$1,980",
        total_platform_price: "$299",
        final_package_price: "$2,279",
      },
      {
        name: "Qualified 40",
        leads_per_month: "40",
        price: "$96",
        total_qualified_lead_price: "$3,840",
        total_platform_price: "$599",
        final_package_price: "$4,439",
      },
      {
        name: "Qualified 60",
        leads_per_month: "60",
        price: "$93",
        total_qualified_lead_price: "$5,580",
        total_platform_price: "$699",
        final_package_price: "$6,279",
      },
      {
        name: "Qualified 80",
        leads_per_month: "80",
        price: "$90",
        total_qualified_lead_price: "$7,200",
        total_platform_price: "$799",
        final_package_price: "$7,999",
      },
    ],
  },
  {
    range: "$400k-$500k",
    id: 4,
    data: [
      {
        name: "Qualified 20",
        leads_per_month: "20",
        price: "$109",
        total_qualified_lead_price: "$2,180",
        total_platform_price: "$299",
        final_package_price: "$2,479",
      },
      {
        name: "Qualified 40",
        leads_per_month: "40",
        price: "$106",
        total_qualified_lead_price: "$4,240",
        total_platform_price: "$599",
        final_package_price: "$4,839",
      },
      {
        name: "Qualified 60",
        leads_per_month: "60",
        price: "$102",
        total_qualified_lead_price: "$6,120",
        total_platform_price: "$699",
        final_package_price: "$6,819",
      },
      {
        name: "Qualified 80",
        leads_per_month: "80",
        price: "$99",
        total_qualified_lead_price: "$7,920",
        total_platform_price: "$799",
        final_package_price: "$8,719",
      },
    ],
  },
  {
    range: "$500k+",
    id: 5,
    data: [
      {
        name: "Qualified 20",
        leads_per_month: "20",
        price: "$129",
        total_qualified_lead_price: "$2,580",
        total_platform_price: "$299",
        final_package_price: "$2,879",
      },
      {
        name: "Qualified 40",
        leads_per_month: "40",
        price: "$125",
        total_qualified_lead_price: "$5,000",
        total_platform_price: "$599",
        final_package_price: "$5,599",
      },
      {
        name: "Qualified 60",
        leads_per_month: "60",
        price: "$121",
        total_qualified_lead_price: "$7,260",
        total_platform_price: "$699",
        final_package_price: "$7,959",
      },
      {
        name: "Qualified 80",
        leads_per_month: "80",
        price: "$117",
        total_qualified_lead_price: "$9,360",
        total_platform_price: "$799",
        final_package_price: "$10,159",
      },
    ],
  },
];

export default page_prices;
